CREATE DATABASE GOOGLE_SCHOLAR;
USE GOOGLE_SCHOLAR;

CREATE TABLE PERFIL(
    id_perfil INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(200) NOT NULL,
    institucion VARCHAR(100),
    foto VARCHAR(200)
);

CREATE TABLE ARTICULO(
    id_articulo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id_perfil INT NOT NULL,
    titulo VARCHAR(100) NOT NULL,
    nro_citas INT NOT NULL,
    anio INT
);

ALTER TABLE ARTICULO ADD FOREIGN KEY(id_perfil) REFERENCES PERFIL(id_perfil);